### ISSUE TITLE
درخواست لیست شدن یک مقاله در سایت ضیا صدر

### ISSUE THREAD

**Issue by bitcoind-me** [bitcoind-me/bitcoind-me#10]
مقاله در آدرس زیر قابل مشاهده است
https://www.ziyasadr.com/2021/01/16/bitcoin-liberty-borderless/

**Comment by n1rna** [comment]
من نظری ندارم که این بلاگ پست رو به کدوم یکی از بخش های موجود فعلی میشه اضافه کرد. 

شاید بد نباشه که یک بخش با عنوان «بلاگ پست ها» یا «ترجمه» اضافه کنیم و این مقاله رو توی اون بخش قرار بدیم.

**Comment by bitcoind-me** [comment]
<div dir=rtl>
به فکر اضافه کردن یک بخش جدید هستیم که مطالب کوتاه‌تر در آن قرار گیرند.
</div>
