### ISSUE TITLE
درخواست لیست شدن آموزش پلتفرم وام هودل هودل

### ISSUE THREAD

**Issue by bitcoind-me** [bitcoind-me/bitcoind-me#12]
<div dir=rtl>
این راهنما توسط کاربر توئیتر @MGatmiri ترجمه شده و در اختیار سایت قرار گرفته

فایل ترجمه:
https://gofile.io/d/xXb9wY

لینک به مقاله اصلی:
https://hodlhodl.medium.com/lend-at-hodl-hodl-step-by-step-guide-51853fdfbed6

</div>

**Comment by n1rna** [comment]
لینک به فایل ترجمه قابل دسترسی نیست.

**Comment by mgatmiri** [comment]
در لینک های زیر مجدد آپلود شد

https://gofile.io/d/v4D4ZC

[Hodl-hodl lending.pdf](https://github.com/bitcoind-me/bitcoind-me/files/6264371/Hodl-hodl.lending.pdf)

[راهنمای گام به گام استقراض در هودل.docx](https://github.com/bitcoind-me/bitcoind-me/files/6264372/default.docx)
