### ISSUE TITLE
ارتقا یا اپگریت رابط کاربری سایت

### ISSUE THREAD

**Issue by tawanabit** [bitcoind-me/bitcoind-me#20]
درود
باتوجه وضعیت کنونی وبسایت بنده حاضرم رابط کاربری و پوسته سایت رو به رایگان به بهترین نحو تغییر بدم 
اگر پیشنهاد یا نمونه ای دارید در صورت موافقت با اصل موضوع بفرمایید
و اگر رد میکند لطفا یک دلیل برای رد کردن این درخواست بیاورید

**Comment by bitcoind-me** [comment]
<div dir=rtl>
از ایده شما استقبال می‌کنیم دوست گرامی.  لطفا یک ایمیل به آدرس سایت ارسال کنید تا برای ادامه کار در ارتباط باشیم.
</div>
bitcoind_me(at)protonmail(.)com

**Comment by tawanabit** [comment]
درود بر شما
ایمیل ارسال شد
