### ISSUE TITLE
Justify Paragraphs

### ISSUE THREAD

**Issue by CronusCipher** [bitcoind-me/bitcoind-me#23]
چرا در بعضی از کتاب ها، مخصوصا موارد اخیر مثل «در جستجوی پول نقد دیجیتال» متن به صورت جاستیفای نیست؟
بهتر است هنگام صفحه آرایی حتما به این موضوع توجه شود

**Comment by bitcoind-me** [comment]
<p dir=rtl>
دوست عزیز این تصمیم بخش صفحه آرایی سایته و ما هم تا امروز به این تصمیم احترام گذاشیتم. از اینکه نظرتون رو برای مانوشتین ازتون متشکریم.
</p>
