### ISSUE TITLE
“درخواست اصلاح لینک به ”مطلب مروری بر روش‌های امن نگهداری از بیت‌کوین

### ISSUE THREAD

**Issue by mgatmiri** [bitcoind-me/bitcoind-me#31]
لینک روی متن مطلب ”مروری بر روش‌های امن نگهداری از بیت‌کوین“ به اشتباه به مقاله‌ی ”در جست‌وجوی بیت‌کوین بعدی“ ارجاع می‌شه.
![bitcoind-issue](https://github.com/bitcoind-me/bitcoind-me/assets/80154454/41aec1a7-26d7-49ce-b519-ee7942262158)

**Comment by bitcoind-me** [comment]
اصلاح شد
