### ISSUE TITLE
افزودن ویدیوهای جادی

### ISSUE THREAD

**Issue by LordArma** [bitcoind-me/bitcoind-me#5]
سلام. جادی ویدیوهای خوبی در مورد بلاکچین و بیت‌کوین در این پلی لیست داره:
https://youtube.com/playlist?list=PL-tKrPVkKKE1gLxAL-56H-XR-fTapqofC

این ویدیوها بسیار معروف هستند.

دلیل خاصی داره که اضافه نشده‌اند؟

لطفاً بررسی بفرمایید و اگر لازم به کمک بود برای درجشون کمک کنم.

**Comment by bitcoind-me** [comment]
<div dir=rtl>
سلام
ممنون بابت معرفی این لیست

آنها را درنظر می گیریم
<br/>
شما این ویدیوها رو شخصا دیده اید؟
</div>

**Comment by LordArma** [comment]
> سلام ممنون بابت معرفی این لیست
> آنها را درنظر می گیریم
> 
> 
> شما این ویدیوها رو شخصا دیده اید؟

من کامل ندیدم. ولی در جلسه اول در مورد رفرنس ویدیوها صحبت میشه. در واقع مبحث بر اساس اون کتاب رفرنس پیش میره. خود جادی هم که شناخته شده هست و در سایر ویدیوهای تخصصی که ازش دیدم هیچوقت مبحث پرت نداشته.

**Comment by ohmydevops** [comment]
سلام. من ویدیو‌ها رو دیدم. به نظرم توضیحات ساده و قابل فهمی داره و اگر کسی بخواد دنبال کنه ارزشمنده

**Comment by mcsaeid** [comment]
> شما این ویدیوها رو شخصا دیده اید؟

من این ویدئوها رو دیده‌م. بسیار مفیدن، به‌خصوص اگه تازه‌وارد باشید. این پلی‌لیست رو به افرادی که تازه با بیت‌کوین آشنا می‌شن پیشنهاد داده‌م، ازجمله خانواده، و برای اون هم مفید بوده. پیشنهاد می‌کنم به سایت افزوده بشن.

**Comment by bitcoind-me** [comment]
<p dir=rtl>
 این ایشو رو به یکی از دوستان تحریریه سپردیم و قراره تصمیم گیری بشه درباره ش. تشکر از دوستانی که توی این ایشو نظر دادن.
</p>
