### ISSUE TITLE
درخواست لیست شدن مقاله در مورد ماینینگ

### ISSUE THREAD

**Issue by bitcoind-me** [bitcoind-me/bitcoind-me#6]
<div dir=rtl>
آقای زجاجی از طریق دایرکت توئیتر درخواست کردن مقاله ویرگول شون درباره ماینینگ توی سایت لیست بشه.
اینجا لینکش رو اضافه میکنم تا نظر بدیم و درباره اش تصمیم بگیریم
لینک مقاله:
</div>

[https://vrgl.ir/VZ5W7](url)

**Comment by Ziya-Sadr** [comment]
عنوان مطلب - از سیر تا پیاز - یعنی مطلب کاملی هستش در صورتی که این مقاله یک روایت مناسب برای شرح ماینینگ به تازه‌واردان دنیای بیتکوین هستش. بخش استخراج غیرمتمرکزها در کتاب کوچک بیتکوین نیز به این مساله به صورت منسجم تری پرداخته است.
به نظر من عنوان مناسبتری برای این مقاله باید انتخاب شود

**Comment by Alireza-Zojaji** [comment]
بله
حق با شما است.
مثلا عنوانش میتونه این باشه:
ماینینگ بیت‌کوین به زبان ساده

**Comment by bitcoind-me** [comment]
<div dir=rtl>
این مقاله رو بررسی کردیم و با توجه به اینکه 

- این موضوع در کتاب کوچک بیت کوین به اختصار و در کتاب اختراع بیت کوین به تفصیل مورد بحث قرار گرفته 
- در حال حاضر بخاطر کمبود فضا در صفحه اول برنامه ای برای لیست کردن مقاله های کوتاه نداریم

امکانش لیست شدنش نیست

</div>
